name: Gthub Action No 1= Automatic

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      with:
        node-version: "16"
    - name: Setup Node
    - run: npm ci
    - name: Build Project
    - run: npm run build